[package]
name = "mystical-runic"
version = "0.3.2"
edition = "2021"
rust-version = "1.74.0"
authors = ["yrbane <yrbane@nethttp.net>"]
description = "🔮 Ancient symbols for modern web magic - A mystical templating engine that weaves HTML from runic incantations"
license = "MIT"
repository = "https://github.com/yrbane/mystical-runic.git"
keywords = ["template", "html", "web", "runic", "magic"]
categories = ["template-engine", "web-programming"]

[dependencies]

[[bin]]
name = "performance_demo"
path = "benchmarks/performance_demo.rs"

[dev-dependencies]