[package]
name = "runic"
version = "0.1.0"
edition = "2021"
authors = ["Chat Team"]
description = "🔮 Ancient symbols for modern web magic - A mystical templating engine that weaves HTML from runic incantations"
license = "MIT"
repository = "https://github.com/yrbane/runic"
keywords = ["template", "html", "web", "runic", "magic"]
categories = ["template-engine", "web-programming"]

[dependencies]
thiserror = "1.0"

[dev-dependencies]
tempfile = "3.8"